--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/n3sa/Wallpapers/2/Snow.jpg"

-- Special
background="#000000"
foreground="#c3c4c5"
cursor="#c3c4c5"

-- Colors
color0="#000000"
color1="#3B698A"
color2="#3F77A1"
color3="#477796"
color4="#487EA1"
color5="#6194AD"
color6="#5F9DC1"
color7="#c3c4c5"
color8="#5c6470"
color9="#3B698A"
color10="#3F77A1"
color11="#477796"
color12="#487EA1"
color13="#6194AD"
color14="#5F9DC1"
color15="#c3c4c5"
